### ISSUE TITLE
NGX-Ellipsis doesnt trigger first time its displayed in my template

### ISSUE THREAD

**Issue by gotwig** [lentschi/ngx-ellipsis#22] opened 2019-07-22 15:09 UTC
Im not sure why, but in my case the "..." and the text shorting only happens after I manualy change the height for example in css in the browser. When the page inititaly loads theres no ellipsis... any idea?

I have the latest angular version, and I checked out the stackblitz, I dont know why this is happening. Do I miss something important? have you experienced this issue?

btw: I dont think its good practise to close tickets directly without getting feedback from the one reporting the issue.

Thank you!

**Comment by lentschi** [comment] 2019-07-23 06:43
@gotwig 

> btw: I dont think its good practise to close tickets directly without getting feedback from the one reporting the issue.

I closed it, because you hardly provided any details other than "it doesn't work". If you would have come up with some way to reproduce your issue, I could have reopened it.

Since you didn't provide a failing StackBlitz, I still have no clue what's going on with your application of the lib. Reading your text, I think **maybe** you have a slight misconception of how `ngx-ellipsis` should work: Any styles need to be set by yourself. (Different users might need different styles, so `ngx-ellipsis` doesn't ever apply any styles such as `height: 100px` on its own - You yourself have to take care of that. That is why in the simple sample in the `README` the code includes `style="width: 100px; height: 100px;"`. )

So please provide a failing StackBlitz (or similar) sample, then I might be able to help you. But I really don't have the time to just guess around.

Also please don't double post: I saw your comment at #20, I just don't always have the time to reply immediately.

**Closed as completed by lentschi** 2019-07-23 06:43 UTC
