### ISSUE TITLE
Showing error while running ng test with angular 13 version

### ISSUE THREAD

**Issue by logerk46** [lentschi/ngx-ellipsis#70] opened 2022-01-17 16:35 UTC
Hi!

I started upgrading to version 13 of Angular and faced an error when running tests:

"Importing EllipsisModule2 which does not have a ɵmod property. "

 Could you clarify when support for version 13 of Angular is planned?

Thanks!

**Comment by lentschi** [comment] 2022-01-21 09:56
@logerk46

It already _should_ support angular 13 - see peer deps: https://github.com/lentschi/ngx-ellipsis/commit/28ddfe6ee38b3e6f8f295cdf6bd99f564e6044cd

I ran the following:

```bash
npx @angular/cli@13 new ang13test
cd ang13test/
npm i --save ngx-ellipsis # -> installed ngx-ellipsis@3.1.6
# -> add EllipsisModule to `app.module` and  ellipsis directive to the `app.component`, then write unit tests for it.
npx ng test
```

...and the tests complete successfully. Which precise versions of ngx-ellipsis and angular have you tried this with? Maybe the error could be due to some custom build setting of yours?

**Comment by lentschi** [comment] 2022-02-04 10:03
I'm closing this (cannot reproduce and no answer for 2 weeks).

**Closed as completed by lentschi** 2022-02-04 10:03 UTC
Labels: cannot-reproduce
