### ISSUE TITLE
(ellipsis-click-more) issue

### ISSUE THREAD

**Issue by j4ckp0t85** [lentschi/ngx-ellipsis#30] opened 2019-12-11 15:44 UTC
hi, i've tried your library.

using it out of the box i see a strange behaviour: the anchor for ellipsed text is written as a string.

replacing the code in the ellipsis.directive.ts this way all good:

this.renderer.setProperty(this.innerElem, 'innerHTML', text);

(so using innerHTML)

am i missing something?

**Comment by lentschi** [comment] 2019-12-11 19:10
@j4ckp0t85 That behavior is intended - See the second line of the README: `Supports text only (no html contents)!`

Of course, if you you need this feature (Using html contents in the ellipsis), you may raise a new issue requesting a change.

I've already given it some thought, but it's not as easy as just using `innerHTML` instead of `textContent` in the code like you suggested. See [this StackBlitz sample where I did that](https://stackblitz.com/edit/github-htjn18?file=src%2Fapp%2Fapp.component.html): If you make the ellipsis smaller by dragging its edge, you will reach a point, when you don't see any ellipsis dots at all. This is due to the fact that they are in the middle of a closing tag:
e.g.: `<a _ngcontent-hem-c16="" href="http://www.google.at">irmod</a...`
Of course it would be possible to programmatically determine the last contained node element that still fits inside the ellipsis container and then go and truncate its `innerText`. But that would make performance worse - so if anything, I would add it as an optional feature.

Then there's the aspect of styling to think of: Inner ellipsis elements could be styled to have `position: absolute`, `margin-left: -50px` or other crazy things which would make the calculation impossible. It could be argued, that not doing such things would lie in the user's responsibility, but I already dread the amount of incoming issues due to such styles.

Lastly, I personally find it hard to think of a use case for this: Adding styled/interactive elements to an ellipsis text will usually produce a design that appears cluttered. (Ellipsis elements are normally used on an overview page, where there's already a lot to see. But of course, that is just a lame excuse, cause I'm sure *someone* will find a use for it ;-) )

**Comment by j4ckp0t85** [comment] 2019-12-11 19:17
Thank you for your response. I'm talking about of text only content. 
Using textContent i don't see the anchor rendered with the text 'More..', i see it at normal text.

I hope you understand me, i'm typing from my phone now

**Comment by lentschi** [comment] 2019-12-11 19:26
Aah, you're talking about `(ellipsis-click-more)` - You're right, I can confirm there's a bug there. It has been introduced in ec20d2486 when trying to fix #29 - apparently that had an unwanted side effect.
I'll look into it as soon as I can.  (Until then, you can revert to `2.0.9`)

**Comment by j4ckp0t85** [comment] 2019-12-11 19:34
Yup! Ok thanks

**Comment by lentschi** [comment] 2019-12-11 20:31
@j4ckp0t85 Fixed in version `2.1.1`
Thanks for reporting this!

**Comment by lentschi** [comment] 2019-12-14 17:01
Unfortunately my fix in 8e8833b was faulty: Adding a padding to the more anchor element (`a.ngx-ellipsis-more`) will cause parts of the `ellipsisCharacters` to exceed the container element's dimensions.

**Closed as completed** 2019-12-14 17:03 UTC
Labels: bug

**Comment by lentschi** [comment] 2019-12-14 18:19
@j4ckp0t85 I just released `ngx-ellipsis 2.1.2` which fixes it for good. (See above comment on why it wasn't properly fixed before - Sorry for any inconvenience)
