### ISSUE TITLE
Ellipsis and click more on next line

### ISSUE THREAD

**Issue by unlight** [lentschi/ngx-ellipsis#28] opened 2019-10-22 18:16 UTC
Hi, @lentschi
Thank you for awesome plugin.

But I'm having issues with adding ellipsis and more link on next line.

<details>
<summary>My goal</summary>
<img src="https://user-images.githubusercontent.com/301732/67315713-3349b700-f518-11e9-8527-6440e02ac6e8.png" />
</details>

I can style `a.ngx-ellipsis-more` as display block, but in this case ellipsis goes on next line too.
Is it possible to separate `ellipsis` and `more-click` element?

**Comment by lentschi** [comment] 2019-10-24 21:48
Hi @unlight!

I believe this is a duplicate of #19 (See the explanation and link there to see how to get it to work.)
If not, please explain how your requirement differs.

Cheers

**Closed as completed by lentschi** 2019-10-24 21:48 UTC
Labels: duplicate

**Comment by unlight** [comment] 2019-10-24 22:13
Yes, that's what I need. Thank you.
