### ISSUE TITLE
Angular 8 peer incompatibility version issue

### ISSUE THREAD

**Issue by edlangjr** [lentschi/ngx-ellipsis#17] opened 2019-05-30 15:22 UTC
When attempting to upgrade a project from Angular 7 to Angular 8, receiving an error:

ng update @angular/cli @angular/core

Package "ngx-ellipsis" has an incompatible peer dependency to "@angular/common" (requires "^>=6.0.0 <8.0.0 || >7.0.0-beta <8.0.0", would install "8.0.0").
Package "ngx-ellipsis" has an incompatible peer dependency to "@angular/core" (requires "^>=6.0.0 <8.0.0 || >7.0.0-beta <8.0.0", would install "8.0.0").
Incompatible peer dependencies found. See above.

Please review and update npm package for ngx-ellipsis to be compatible with Angular 8+

**Comment by lentschi** [comment] 2019-06-07 11:31
@edlangjr Thanks for the hint - Updated to angular 8 in `ngx-ellipsis@2.0.3`

**Comment by kettunen** [comment] 2019-06-13 09:38
I still have error upgrading to Angular 8 with ngx-ellipsis@2.0.3:

ng update @angular/cli @angular/core
Package "ngx-ellipsis" has an incompatible peer dependency to "@angular/common" (requires "^>=6.0.0 <9.0.0 || >7.0.0-beta <9.0.0", would install "8.0.0").
Package "ngx-ellipsis" has an incompatible peer dependency to "@angular/core" (requires "^>=6.0.0 <9.0.0 || >7.0.0-beta <9.0.0", would install "8.0.0").

**Comment by lentschi** [comment] 2019-06-21 08:10
@kettunen Thanks for your report, but I'm unable to reproduce your problem:

```bash
cd /tmp/
ng new ngx-ellipsis-test
cd ngx-ellipsis-test/
npm i --save ngx-ellipsis@2.0.3
```

... just gives me the all time classic "you're not using a Mac" warning:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```
Could you please compare you're installed packages with mine (or, if it's a public project anyway, share your source code with me somehow):

```bash
npm list | grep -E "angular|ellipsis"
ngx-ellipsis-test@0.0.0 /tmp/ngx-ellipsis-test
├─┬ @angular-devkit/build-angular@0.800.3
│ ├─┬ @angular-devkit/architect@0.800.3
│ │ ├── @angular-devkit/core@8.0.3 deduped
│ ├─┬ @angular-devkit/build-optimizer@0.800.3
│ ├─┬ @angular-devkit/build-webpack@0.800.3
│ │ ├── @angular-devkit/architect@0.800.3 deduped
│ │ ├── @angular-devkit/core@8.0.3 deduped
│ ├─┬ @angular-devkit/core@8.0.3
│ │ ├── @angular-devkit/core@8.0.3 deduped
├─┬ @angular/animations@8.0.2
├─┬ @angular/cli@8.0.3
│ ├── @angular-devkit/architect@0.800.3 deduped
│ ├── @angular-devkit/core@8.0.3 deduped
│ ├─┬ @angular-devkit/schematics@8.0.3
│ │ ├── @angular-devkit/core@8.0.3 deduped
│ ├─┬ @schematics/angular@8.0.3
│ │ ├── @angular-devkit/core@8.0.3 deduped
│ │ └── @angular-devkit/schematics@8.0.3 deduped
│ │ ├── @angular-devkit/core@8.0.3 deduped
│ │ ├── @angular-devkit/schematics@8.0.3 deduped
├─┬ @angular/common@8.0.2
├─┬ @angular/compiler@8.0.2
├─┬ @angular/compiler-cli@8.0.2
├─┬ @angular/core@8.0.2
├─┬ @angular/forms@8.0.2
├── @angular/language-service@8.0.2
├─┬ @angular/platform-browser@8.0.2
├─┬ @angular/platform-browser-dynamic@8.0.2
├─┬ @angular/router@8.0.2
├─┬ ngx-ellipsis@2.0.3
```

**Comment by lentschi** [comment] 2019-07-12 07:09
Re-Closing as @kettunen has not responded to my request for clarification...

**Closed as completed by lentschi** 2019-07-12 07:09 UTC
